// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Context;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(EmpContext))]
    partial class EmpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            Name = "Marsel",
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            Name = "Alice",
                            Title = "HR Manager"
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            Name = "Bob",
                            Title = "Sales Executive"
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            Name = "John",
                            Title = "Marketing Specialist"
                        },
                        new
                        {
                            Id = 5,
                            Age = 27,
                            Name = "Emily",
                            Title = "Accountant"
                        },
                        new
                        {
                            Id = 6,
                            Age = 29,
                            Name = "David",
                            Title = "Graphic Designer"
                        },
                        new
                        {
                            Id = 7,
                            Age = 32,
                            Name = "Sophia",
                            Title = "Project Manager"
                        },
                        new
                        {
                            Id = 8,
                            Age = 24,
                            Name = "Liam",
                            Title = "Customer Support"
                        },
                        new
                        {
                            Id = 9,
                            Age = 31,
                            Name = "Olivia",
                            Title = "Operations Manager"
                        },
                        new
                        {
                            Id = 10,
                            Age = 26,
                            Name = "Michael",
                            Title = "Software Developer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
